### ISSUE TITLE
Error: Export historical events not found for plugin 

### ISSUE THREAD

**Issue by code-constructor** [PostHog/posthog-plugin-migrator3000#10]
I've installed the plugin into my hosted posthog instance. After enabling and configuring of the plugin i've alway get the Error: "Task "Export historical events" not found for plugin "Migrator 3000 (Beta)" with config id [object Object]".

Is there any solution for this problem? Thanks in advance!

![Bildschirmfoto 2022-03-13 um 22 04 32](https://user-images.githubusercontent.com/579635/158079387-bb835f8f-4283-4cc5-a8dc-6f8741251382.png)

**Comment by tiina303** [comment]
What deployment option do you have: hobby? AWS? DigitaOcean? GCP?
What version of PostHog are you using on your self-hosted instance? 
Are you running on master by any chance, if so we did turn export historical events off for a brief period over the weekend and you could be on one of those commits, but it has been turned on again now. We suggest using release tags for the Posthog version you're using.

**Comment by code-constructor** [comment]
Hi @tiina303, the instance is hosted by Posthog: https://posthog.com/. So i've did not selfhost anything.

**Comment by yakkomajuri** [comment]
@code-constructor could you try again? This was briefly disabled for 48 hours given an issue we found

**Comment by code-constructor** [comment]
@yakkomajuri yes it works. Thanks a lot!
