### ISSUE TITLE
Migration fails with "Export historical events not found for plugin" error

### ISSUE THREAD

**Issue by msmans** [PostHog/posthog-plugin-migrator3000#17]
We are trying to migrate our data from a hobby instance at version 1.35.0 to a self hosted kubernetes instance at version 1.39.1 and getting the following error after configuring and enabling the migrator plugin with version config set to `1.30.0+`.

```
Task "Export historical events" not found for plugin "Migrator 3000 (Beta)" with config id [object Object]
```

With debug on, after the above log, there are no more logs and no events are migrated.

**Comment by macobo** [comment]
Hi! We disabled historic exports for a while around that version. I'd recommend upgrading to latest version first and retrying the export.
