### ISSUE TITLE
Steps needed to run this plugin on cloud?

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog-plugin-migrator3000#4]
What do we need to do to run this on cloud? Are we concerned about people abusing this export/causing lots of resource usage for us?

@yakkomajuri

**Comment by avk** [comment]
The Heroku stack being deprecated makes me curious about this too. Would be great to move my small data off of a self-hosted instance onto cloud.

**Comment by tiina303** [comment]
@avk you can move into cloud as you'll be using the plugin on your instance and your cloud account will just see it as normal ingestion, reach out in the user slack if you run into any problems :) This task is more about being able to migrate from cloud to self-hosted, when you'd need to run the plugin on cloud.

**Comment by yakkomajuri** [comment]
Yeah I was being a bit cautious putting this out on Cloud as it sort of incentivizes people to run these long exports. Realistically though you could trigger just as heavy of an export with the replicator plugin so if someone has requested this we can probably make it available

**Comment by paolodamico** [comment]
Another [user](https://app.papercups.io/conversations/all/4733d3d1-1944-4cc5-81ea-1b6d9f7c2928) interested in this migration from Cloud -> Self-hosted. 

Maybe we could do a DNS validation on the domain to make sure the user running the export has actual authority over the domain? And avoid potential DDoS attacks.

**Comment by yakkomajuri** [comment]
I've enabled this on Cloud. People could achieve what this plugin does in a myriad other ways. 

As for what you mentioned @paolodamico, that's a separate discussion we've had and should revisit soon.
