### ISSUE TITLE
Min version of Posthog to run?

### ISSUE THREAD

**Issue by avk** [PostHog/posthog-plugin-migrator3000#5]
What's the minimum version of Posthog this plugin runs on? When I tried on Posthog 1.29, I saw this ERROR in the plugin log:

`Task "Export historical events" not found for plugin "Migrator 3000 (Beta)" with config id [object Object]`

**Comment by yakkomajuri** [comment]
I have confirmed this should work on PostHog 1.29.0. 

Can you send me a screenshot of your system status on the instance you've enabled this plugin in?

**Comment by avk** [comment]
Sorry, I misspoke, I was on 1.27.0. 

I can try to upgrade to 1.29.0 or 1.29.1 as I've been [having issues](https://github.com/PostHog/posthog/issues/7408#issuecomment-1014614188) upgrading to 1.30.0 on Heroku.

**Comment by avk** [comment]
On 1.27.0 here's my system status:

![image](https://user-images.githubusercontent.com/28668/149793967-bb4a4d3c-ded3-4133-a48b-381fdc0ab5e5.png)

**Comment by avk** [comment]
1.29.1 is working for me! Cheers!
