### ISSUE TITLE
Is there a method to migrate data with manage.py?

### ISSUE THREAD

**Issue by stephane-klein** [PostHog/posthog-plugin-migrator3000#8]
I searched unsuccessfully for a method to migrate the events... data from `PostgreSQL` to `ClickHouse` (on Self Hosted instance).
I think [`SKIP_ASYNC_MIGRATIONS_SETUP=0 python manage.py migrate_clickhouse`](https://github.com/PostHog/posthog/blob/10dfd7e89aa91a3adaeafecd065fa7992efc0db8/ee/management/commands/migrate_clickhouse.py) only creates the data model but does not migrate the data.

Question: is there any other method than [posthog-plugin-migrator3000](https://github.com/PostHog/posthog-plugin-migrator3000) to migrate the data?

I think a direct migration from `PostgreSQL` to `ClickHouse` must be faster than going through the Rest API (although I know it is not suitable for migrating data to or from a cloud instance).

If there is no other migration method, how about adding this information in the [README](https://github.com/PostHog/posthog-plugin-migrator3000/blob/main/README.md)? And add the rational?

**Comment by timgl** [comment]
Hey there! The way we migrate data is tightly coupled to how the plugins work. We don't offer another way of migrating and are not planning on offering one. Will have a look at your other issues today.
